apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-bigquery-sink
    team: teamdigihot
  name: hm-bigquery-sink
  namespace: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  strategy:
    type: Recreate
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  gcp:
    bigQueryDatasets:
      - name: hm_bigquery_sink_v1_dataset_prod
        permission: READWRITE
