apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: pia-bigquery-sink
    team: pia
  name: pia-bigquery-sink
  namespace: pia
spec:
  image: {{ image }}
  strategy:
    type: Recreate
  liveness:
    path: /internal/isalive
  readiness:
    path: /internal/isready
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: loki
        - id: elastic
  replicas:
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
  secureLogs:
    enabled: true
  gcp:
    bigQueryDatasets:
      - name: pia_bigquery_sink_v1_dataset_dev
        permission: READWRITE
  env:
    - name: BIGQUERY_DATASET_ID
      value: pia_bigquery_sink_v1_dataset_dev
