apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: pia-bigquery-sink
    team: pia
  name: pia-bigquery-sink
  namespace: pia
spec:
  image: {{ image }}
  team: pia
  strategy:
    type: Recreate
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  envFrom:
    - secret: bigquery-hash-suffix
  gcp:
    bigQueryDatasets:
      - name: pia_bigquery_sink_v1_dataset_prod
        permission: READWRITE
  env:
    - name: IA_SAK_HENDELSE_TOPIC
      value: pia.ia-sak-hendelse-v1
    - name: IA_SAK_TOPIC
      value: pia.ia-sak-v1
