apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: pia-bigquery-sink
    team: pia
  name: pia-bigquery-sink
  namespace: pia
spec:
  image: {{ image }}
  team: pia
  strategy:
    type: Recreate
  liveness:
    path: /internal/isalive
  readiness:
    path: /internal/isready
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  gcp:
    bigQueryDatasets:
      - name: pia_bigquery_sink_v1_dataset_prod
        permission: READWRITE
  env:
    - name: BIGQUERY_DATASET_ID
      value: pia_bigquery_sink_v1_dataset_prod
    - name: IA_SAK_STATISTIKK_TOPIC
      value: ia-sak-statistikk-v1
    - name: KAFKA_TOPIC_PREFIX
      value: "pia"
